### ISSUE TITLE
Can't get extractnet to work -> regex._regex_core.error: bad escape \d at position 7

### ISSUE THREAD

**Issue by mowsen** [currentslab/extractnet#12]
Hey, 

I tried to make extractnet work on my Macbook Pro with M1 chip.

I tried several python versions (3.9.9 / 3.10.4) with the same result (extractnet installed through pip). 

This is what I'm getting:

<img width="1050" alt="Screenshot 2022-11-17 at 22 23 30" src="https://user-images.githubusercontent.com/45080170/202562719-7c526202-1cae-474a-ac2e-043a3ac9eae6.png">

Any ideas how this can be solved?

Thanks

**Comment by mowsen** [comment]
Sorry, just found a way to get it working:

pip uninstall regex -y
pip install regex==2022.3.2

See here: [https://stackoverflow.com/questions/71498132/error-in-heroku-regex-regex-core-error-bad-escape-d-at-position-7-when-usin](https://stackoverflow.com/questions/71498132/error-in-heroku-regex-regex-core-error-bad-escape-d-at-position-7-when-usin)

**Comment by fubz** [comment]
This can be fixed by upgrading instead of downgrading now.  In requirements.txt set dateparser to 1.2.0
